### ISSUE TITLE
IllegalArgumentException: endIndex < beginIndex instead of a ParseTree for some parse errors

### ISSUE THREAD

**Issue by csamak** [jparsec/jparsec#68]
For some invalid input to my parser, calling `.parseTree` on the parser is throwing the below exception. Other invalid input works fine with the same parser. Getting an error message through a non-debug mode `.parse` works fine for all invalid input.

Debugging reveals that it's trying to set a `TreeNode`'s end index to `0` when building a `ParseTree`.

```
java.lang.IllegalArgumentException: endIndex < beginIndex
	at org.jparsec.internal.util.Checks.checkArgument(Checks.java:45)
	at org.jparsec.TreeNode.setEndIndex(TreeNode.java:69)
	at org.jparsec.TreeNode.freeze(TreeNode.java:116)
	at org.jparsec.ParseContext.buildErrorParseTree(ParseContext.java:212)
	at org.jparsec.ScannerState.run(ScannerState.java:81)
	at org.jparsec.Parser.parseTree(Parser.java:873)
        ...
```

From debugging, in ScannerState.run the `ParserException` before `exception.setParseTree` is:

```
org.jparsec.error.ParserException: line 1, column 28:
LABEL1 or LABEL2 expected, EOF encountered.
```

I am trying to create a simple case to reproduce the error and will update this issue if I am successful.

**Comment by csamak** [comment]
Ok the following reproduces this:

```
Terminals terms = Terminals.operators("?").words(Scanners.IDENTIFIER).keywords("key").build();
Parser<?> simple = identifier().next(Parsers.or(identifier(), terms.token("key").label("inner")).label("outer")).many();
ParseTree tree = simple.from(terms.tokenizer(), Scanners.WHITESPACES).parseTree("A ?");
```
Running the above results in:
```
java.lang.IllegalArgumentException: endIndex < beginIndex

	at org.jparsec.internal.util.Checks.checkArgument(Checks.java:45)
	at org.jparsec.TreeNode.setEndIndex(TreeNode.java:69)
	at org.jparsec.TreeNode.freeze(TreeNode.java:116)
	at org.jparsec.ParseContext.buildErrorParseTree(ParseContext.java:212)
	at org.jparsec.ScannerState.run(ScannerState.java:81)
	at org.jparsec.Parser.parseTree(Parser.java:873)
        ...
```

Change `.parseTree` to `.parse` though, and the error message is:

```
org.jparsec.error.ParserException: line 1, column 3:
inner or outer expected, ? encountered.
```

Removing either label `outer` or `inner` also results in an expected/encountered error message. Together though, it's `endIndex < beginIndex`
